apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/geilername/argo-demo.git
    targetRevision: HEAD
    path: gitops
  destination:
    server: KUBERNETESAPIADDR
    namespace: demo-workloads