apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: demo-workloads
  name: argocd-robot
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-edit-binding
  namespace: demo-workloads
subjects:
- kind: ServiceAccount
  name: argocd-robot
  namespace: demo-workloads
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: ""